### ISSUE TITLE
VM Linux uniquement

### ISSUE THREAD

**Issue by SimonDevelop** [Estylos/CPCDOS-RASPBERRY-PI-ARDUINO#1]
Salut, je voulais savoir si il est possible d'utiliser uniquement des scripts python via une machine virtuel linux pour envoyer des actions sur l'arduino ? Comment tu procède pour cette liaison ?

Ton projet est vraiment incroyable bravo à toi, mais c'est possible d'utiliser moins de matériels ? (virtual machine linux puis arduino pour mon cas).
Je ne connais pas encore très bien cpcdos... #Sorry

J'ai aussi vu ton poste complet sur "http://www.developpez.net" et pour te facilité la création de schéma électronique tu as le logiciel "fritzing" que tu peux télécharger gratuitement sur le site officiel, voilà c'est câdeau ;)

Cordialement, Fukotaku

**Comment by Estylos** [comment]
Salut, oui c'est tout à fait possible ! 

Je viens de tester à l'instant ce que tu m'as dit : 

J'ai connecté mon Arduino à mon pc (qui tourne sur Windows 10), j'ai partagé port USB de l'Arduino avec Ubuntu sur VirtualBox (Configuration -> USB ->  Clique sur le logo USB avec un "+" en vert -> Arduino) et j'ai lancer ce script Python : 

[python.zip](https://github.com/Estylos/CPCDOS-RASPBERRY-PI-ARDUINO/files/220799/python.zip) (je le mets dans un zip car GitHub fait n'importe quoi quand je le mets dans la balise code...).

Ensuite, j’exécute ce code, toujours sur Ubuntu, en tant que root et il me demande d'entrer quelque chose : ##1, ##2, ##3, ##4, ##5, ##6, ##clear, ##l1, ##l2 ou du texte. (Tu peux retrouver leurs significations dans le ficher "LCD_LEDS.ino" (qui doit être mit impérativement avant sur l'Arduino)).

Voilà, j'espère t'avoir aidé ;)

PS : Je connaissais déjà fritzing, mais j'ai préféré le faire avec PhotoFiltre car sinon, je pense que je ne pouvais pas mettre les logos de PHP, Cpcdos, Python, USB... Mais c'est vrai que pour les schémas de câblages, ça facilite la vie :p .

**Comment by SimonDevelop** [comment]
Je suis en train de préparer le test, merci en tous cas tu m'a données des idées ^^
PS: Le faite d’exécuter les scripts python en sudo via php il y as pas de problème ? genre le faite que php ne donne pas le mdp root ?

**Comment by Estylos** [comment]
D'accord, tu me tiens au courant :)

Un petit peu ^^ enfin ça dépend, et non on ne donne pas le mot de passe root, il faut inscrire "www-data" dans le fichier sudoers. Plus d'informations ici : http://blogmotion.fr/systeme/executer-un-script-shell-avec-permission-root-en-php-1312

**Comment by SimonDevelop** [comment]
Un grand merci, un problème de réglé ! mais...

Enfaite je bloque dans la partie arduino, qu'en j’exécute ma page php qui envois l'argument au script python et l’envoie lui à l'arduino, tous ça fonctionne, mais je pense que je n'est pas bien compris le schéma de câblage de l'arduino... 

Sans vouloir t’offenser j'ai du mal à visualiser ton schéma et du coup je fait n'importe quoi '-'
Mais l'arduino reçois bien l'information, la led orange de la carte clignote au moment de l'envoie.

Sinon c'est que ça vien peut-être aussi de mon code arduino, le voici :

```
#define LED1 2
String content = ""; 
char character;

void setup() {

  pinMode(LED1, OUTPUT);

  Serial.begin(9600);

}

void loop() {

  delay(50); // on attend 50 ms

  while(Serial.available()) { // si des données entrantes sont présentes
    character = Serial.read(); // on les récupères une par une (caractère par caractère)
    content.concat(character); // on ajoute les caractères un à la suite (exemple : l + c + d = lcd) 
  }

  if (content == "##1") { // si on récupère ##1
    digitalWrite(LED1, HIGH); // alors on allume la LED
    content = ""; // on efface ce que linux a envoyé précédemment
  }

  else if (content == "##0") { // si on récupère ##0
    digitalWrite(LED1, LOW); // alors on eteind la LED
    content = ""; // on efface ce que linux a envoyé précédemment
  }

}
```

Edit: C'est bon j'ai trouver ça marche ! (Je suis heureux bordel de merde !)
Merci pour le partage de ton projet, cela m'a beaucoup appris dans l'utilité de l'arduino et python :)

**Comment by Estylos** [comment]
Je ne pense pas que cela vient du code, il m'a

**Comment by Estylos** [comment]
Ah super ! C'était quoi le problème ?

**Comment by SimonDevelop** [comment]
J'avais pas mis ce bout de code... ^^'

```
delay(50); // on attend 50 ms

  while(Serial.available()) { // si des données entrantes sont présentes
    character = Serial.read(); // on les récupères une par une (caractère par caractère)
    content.concat(character); // on ajoute les caractères un à la suite (exemple : l + c + d = lcd) 
  }
```

**Comment by Estylos** [comment]
Ah bah oui, en effet ^^ Sans ça, l'Arduino ne peut pas récupérer le contenu envoyé ^^

Et conseil, rajoute ça après le `else if` pour que quand on envoie autre chose que ##1 ou ##2, le contenu ne reste pas dans la variable "content" ;)

```
else
{
  content = "";
}
```

**Comment by SimonDevelop** [comment]
Bien vu encore merci !
